"""请求控制基础组件（设计文档 7、8）。

所有参数均为本工具的保守初始值，不是 12306 公布的配额。
组件使用可注入时钟与随机源，保证测试确定性。
"""
import random
import time
from collections.abc import Callable

# 读取重试：同一操作最多 3 次重试，指数退避 30/60/120 秒。
READ_RETRY_DELAYS: tuple[float, ...] = (30.0, 60.0, 120.0)
# 通知 outbox 重试：30/120/300 秒各一次。
NOTIFY_RETRY_DELAYS: tuple[float, ...] = (30.0, 120.0, 300.0)
# 429 无 Retry-After 时的默认冷却。
DEFAULT_RATE_LIMIT_COOLDOWN = 300.0
MAX_RATE_LIMIT_COOLDOWN = 1800.0
# 单查询键连续失败熔断。
CIRCUIT_FAILURE_THRESHOLD = 5
CIRCUIT_COOLDOWN = 600.0


def jittered(delay: float, ratio: float, rng: Callable[[], float] = random.random) -> float:
    """只加正向抖动：delay 到 delay*(1+ratio)。"""
    return delay * (1.0 + ratio * rng())


class RetryPolicy:
    """有限次数的指数退避策略。attempt 从 0 计（第一次失败后的等待）。"""

    def __init__(self, delays: tuple[float, ...] = READ_RETRY_DELAYS, ratio: float = 0.2,
                 rng: Callable[[], float] = random.random):
        if not delays:
            raise ValueError("delays must not be empty")
        self.delays = delays
        self.ratio = ratio
        self.rng = rng

    @property
    def max_attempts(self) -> int:
        return len(self.delays)

    def delay_for(self, attempt: int) -> float:
        base = self.delays[min(max(attempt, 0), len(self.delays) - 1)]
        return jittered(base, self.ratio, self.rng)


class RateLimiter:
    """Reusable operation gate. Real adapter wiring is deliberately not enabled."""

    def __init__(self, interval: float = 15.0, clock: Callable[[], float] = time.monotonic):
        if interval <= 0:
            raise ValueError("interval must be positive")
        self.interval = interval
        self.clock = clock
        self.next_allowed = float("-inf")

    def reserve(self) -> float:
        now = self.clock()
        scheduled = max(now, self.next_allowed)
        self.next_allowed = scheduled + self.interval
        return scheduled - now


class CircuitBreaker:
    """单查询键连续 N 次读取失败后熔断一段时间；半开只允许一次探测。"""

    def __init__(self, threshold: int = CIRCUIT_FAILURE_THRESHOLD, cooldown: float = CIRCUIT_COOLDOWN,
                 clock: Callable[[], float] = time.monotonic):
        if threshold < 1 or cooldown <= 0:
            raise ValueError("threshold must be >= 1 and cooldown must be positive")
        self.threshold = threshold
        self.cooldown = cooldown
        self.clock = clock
        self._failures: dict[str, int] = {}
        self._open_until: dict[str, float] = {}
        self._probing: set[str] = set()

    def allow(self, key: str) -> bool:
        if key in self._probing:
            return False
        now = self.clock()
        until = self._open_until.get(key)
        if until is None:
            return True
        if now < until:
            return False
        self._probing.add(key)  # 半开：放行一次探测
        return True

    def is_probing(self, key: str) -> bool:
        return key in self._probing

    def record_success(self, key: str) -> None:
        self._failures.pop(key, None)
        self._open_until.pop(key, None)
        self._probing.discard(key)

    def record_failure(self, key: str) -> None:
        was_probing = key in self._probing
        self._probing.discard(key)
        now = self.clock()
        if was_probing:
            # 半开探测失败：重新熔断一个完整冷却期。
            self._open_until[key] = now + self.cooldown
            return
        count = self._failures.get(key, 0) + 1
        self._failures[key] = count
        if count >= self.threshold:
            self._open_until[key] = now + self.cooldown

    def remaining_cooldown(self, key: str) -> float:
        until = self._open_until.get(key)
        if until is None:
            return 0.0
        return max(0.0, until - self.clock())


class CooldownGate:
    """账号级 429/风控冷却：遵守 Retry-After，半开探测失败则冷却翻倍，上限 30 分钟。"""

    def __init__(self, initial: float = DEFAULT_RATE_LIMIT_COOLDOWN,
                 maximum: float = MAX_RATE_LIMIT_COOLDOWN,
                 clock: Callable[[], float] = time.monotonic):
        if initial <= 0 or maximum < initial:
            raise ValueError("require 0 < initial <= maximum")
        self.initial = initial
        self.maximum = maximum
        self.clock = clock
        self._until = float("-inf")
        self._current = initial

    def trigger(self, retry_after_seconds: float | None = None) -> float:
        # An explicit server Retry-After is a minimum. The local cap only
        # applies to cooldowns generated by our own backoff policy.
        if retry_after_seconds is not None:
            self._current = max(float(retry_after_seconds), self.initial)
        else:
            self._current = min(self.initial, self.maximum)
        self._until = self.clock() + self._current
        return self._current

    def allow(self) -> bool:
        return self.clock() >= self._until

    def remaining(self) -> float:
        return max(0.0, self._until - self.clock())

    def half_open(self) -> bool:
        """冷却结束后放行一次只读探测；返回是否还有剩余冷却。"""
        return self.allow()

    def on_rate_limited(self, retry_after_seconds: float | None = None) -> float:
        """收到 429 时的入口：冷却结束后的首次触发视为半开探测失败（冷却翻倍）。"""
        if self._until > float("-inf") and self.clock() >= self._until:
            return self.probe_failed()
        return self.trigger(retry_after_seconds)

    def probe_failed(self) -> float:
        doubled = min(self._current * 2, self.maximum)
        self._current = max(doubled, self.initial)
        self._until = self.clock() + self._current
        return self._current

    def reset(self) -> None:
        self._until = float("-inf")
        self._current = self.initial
