from typing import Protocol

from railassist.domain.models import (
    BookingIntent, CapabilitySet, PreparedOrder, QuerySpec, ReconcileResult,
    SaleTimeQuery, SaleTimeResult, SessionStatus, SubmissionResult, TicketSnapshot,
    UserActionRequired,
)


class RailwayPort(Protocol):
    """铁路服务端口（设计文档 9.3，同步形态）。

    下单与对应核对能力必须同时可用；所有实现不得自行启动无限轮询。
    """

    def capabilities(self) -> CapabilitySet: ...
    def session_status(self) -> SessionStatus: ...
    def open_login(self) -> UserActionRequired: ...
    def query_tickets(self, query: QuerySpec) -> TicketSnapshot: ...
    def query_sale_time(self, query: SaleTimeQuery) -> SaleTimeResult: ...
    def arm_hit_watcher(self, trains: list[str], seat: str, passenger_count: int,
                        from_code: str, to_code: str) -> None: ...
    def check_booking_login(self) -> bool: ...
    def refresh_results(self) -> None: ...
    def read_hit(self) -> str | None: ...
    def prepare_order(self, intent: BookingIntent) -> PreparedOrder: ...
    def submit_order(self, prepared: PreparedOrder) -> SubmissionResult: ...
    def prepare_waitlist(self, intent: BookingIntent) -> PreparedOrder: ...
    def submit_waitlist(self, prepared: PreparedOrder) -> SubmissionResult: ...
    def reconcile(self, attempt: dict) -> ReconcileResult: ...
    def close(self) -> None: ...
