from typing import Protocol
from railassist.domain.models import TaskRecord, TaskStatus


class TaskRepositoryPort(Protocol):
    def create(self, config: dict) -> TaskRecord: ...
    def get(self, task_id: str) -> TaskRecord: ...
    def list_tasks(self) -> list[TaskRecord]: ...
    def update(self, task_id: str, status: TaskStatus, result: dict | None = None) -> TaskRecord: ...

